# Generated by Django 3.1.3 on 2020-11-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_age', models.IntegerField()),
                ('cust_ph_no', models.BigIntegerField()),
                ('cust_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_age', models.IntegerField()),
                ('emp_ph_no', models.BigIntegerField()),
                ('emp_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('body_temp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visit_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDeliveryOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
