# Generated by Django 3.1.3 on 2020-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201208_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storevisit',
            name='body_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
