# Generated by Django 3.1.3 on 2021-01-02 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201220_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='admin_password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
